### ISSUE TITLE
Update Container

### ISSUE THREAD

**Issue by FrankDuchna-Luebbecke** [Rapha-Borges/deploy-vaultwarden#4]
Hello, 
could you add a Documentation/explanation of how to update to the latest vaultwarden Image with your compose-file?
I tried to do docker-compose pull and docker-compose up -d but then it threw me lots of error messages:

Recreating a46194029b86_vaultwarden-backup-1 ...
Recreating 2894fa217823_vaultwarden          ...
Recreating 4a3409a3284c_vaultwarden-nginx-proxy-1 ...

ERROR: for a46194029b86_vaultwarden-backup-1  'ContainerConfig'

ERROR: for 2894fa217823_vaultwarden  'ContainerConfig'

ERROR: for 4a3409a3284c_vaultwarden-nginx-proxy-1  'ContainerConfig'

ERROR: for backup  'ContainerConfig'

ERROR: for vaultwarden  'ContainerConfig'

ERROR: for nginx-proxy  'ContainerConfig'
Traceback (most recent call last):
  File "/usr/bin/docker-compose", line 33, in <module>
    sys.exit(load_entry_point('docker-compose==1.29.2', 'console_scripts', 'docker-compose')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/compose/cli/main.py", line 81, in main
    command_func()
  File "/usr/lib/python3/dist-packages/compose/cli/main.py", line 203, in perform_command
    handler(command, command_options)
  File "/usr/lib/python3/dist-packages/compose/metrics/decorator.py", line 18, in wrapper
    result = fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/compose/cli/main.py", line 1186, in up
    to_attach = up(False)
                ^^^^^^^^^
  File "/usr/lib/python3/dist-packages/compose/cli/main.py", line 1166, in up
    return self.project.up(
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/compose/project.py", line 697, in up
    results, errors = parallel.parallel_execute(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/compose/parallel.py", line 108, in parallel_execute
    raise error_to_reraise
  File "/usr/lib/python3/dist-packages/compose/parallel.py", line 206, in producer
    result = func(obj)
             ^^^^^^^^^
  File "/usr/lib/python3/dist-packages/compose/project.py", line 679, in do
    return service.execute_convergence_plan(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/compose/service.py", line 579, in execute_convergence_plan
    return self._execute_convergence_recreate(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/compose/service.py", line 499, in _execute_convergence_recreate
    containers, errors = parallel_execute(
                         ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/compose/parallel.py", line 108, in parallel_execute
    raise error_to_reraise
  File "/usr/lib/python3/dist-packages/compose/parallel.py", line 206, in producer
    result = func(obj)
             ^^^^^^^^^
  File "/usr/lib/python3/dist-packages/compose/service.py", line 494, in recreate
    return self.recreate_container(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/compose/service.py", line 612, in recreate_container
    new_container = self.create_container(
                    ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/compose/service.py", line 330, in create_container
    container_options = self._get_container_create_options(
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/compose/service.py", line 921, in _get_container_create_options
    container_options, override_options = self._build_container_volume_options(
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/compose/service.py", line 960, in _build_container_volume_options
    binds, affinity = merge_volume_bindings(
                      ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/compose/service.py", line 1548, in merge_volume_bindings
    old_volumes, old_mounts = get_container_data_volumes(
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/compose/service.py", line 1579, in get_container_data_volumes
    container.image_config['ContainerConfig'].get('Volumes') or {}
    ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
KeyError: 'ContainerConfig'



What did I do wrong?
I hope you can help here, because I would like to go to the newest vaultwarden/server

Thank you in advance.

**Comment by Rapha-Borges** [comment]
Hey there, sorry to hear you're running into this. I've tried to recreate the issue on my end, but no luck.

Before proceeding, I recommend backing up your data. By default, Vaultwarden server data is stored in `/opt/vw`, while the rest of the data is located in `~/vaultwarden/data`, `~/vaultwarden/letsencrypt`, and `~/vaultwarden/vaultwarden-backup`.

As a first step to try to fix this problem, I would try removing containers and images from your system.

```
docker compose down
docker ps -a
docker rm <container-id>
docker images
docker image rm <image-id>
```

After that, review your `docker-compose.yaml` and `.env` files, comparing them to what's in the repository. Then, proceed with `docker compose up -d` again.

If it fails, try inspecting the logs with `docker compose logs -f` o running `docker compose up` whitout `-d` for any relevant information.

If none of this works, the error may be related to your OS or Docker installation. Start by reinstalling Docker. If that doesn't work, further investigation of your operating system may be necessary.

Could you provide me with some data to try to reproduce the error? Such as the OS you're using, the version of Docker and Docker Compose.

Thank you for helping me improve the project by reporting this issue. I hope I can help you whit this problem.
